[2025-05-21T17:24:07.293+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-21T17:24:07.326+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitor_PWU.monitor_model manual__2025-05-21T17:24:06.136466+00:00 [queued]>
[2025-05-21T17:24:07.338+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitor_PWU.monitor_model manual__2025-05-21T17:24:06.136466+00:00 [queued]>
[2025-05-21T17:24:07.339+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-21T17:24:07.362+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): monitor_model> on 2025-05-21 17:24:06.136466+00:00
[2025-05-21T17:24:07.371+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'monitor_PWU', 'monitor_model', 'manual__2025-05-21T17:24:06.136466+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/monitor_PWU.py', '--cfg-path', '/tmp/tmpgmbp831h']
[2025-05-21T17:24:07.375+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask monitor_model
[2025-05-21T17:24:07.378+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=224) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-21T17:24:07.379+0000] {standard_task_runner.py:63} INFO - Started process 230 to run task
[2025-05-21T17:24:07.447+0000] {task_command.py:426} INFO - Running <TaskInstance: monitor_PWU.monitor_model manual__2025-05-21T17:24:06.136466+00:00 [running]> on host affaf7e28daa
[2025-05-21T17:24:07.584+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monitor_PWU' AIRFLOW_CTX_TASK_ID='monitor_model' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T17:24:06.136466+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T17:24:06.136466+00:00'
[2025-05-21T17:24:07.586+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-21T17:24:07.631+0000] {logging_mixin.py:188} INFO - [ERROR] Flask 응답 상태: 500
[2025-05-21T17:24:07.631+0000] {logging_mixin.py:188} INFO - [ERROR] 응답 내용: {"error":"[Errno 2] No such file or directory: 'scaler/x_pwu_scaler.pkl'"}
[2025-05-21T17:24:07.632+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-21T17:24:07.632+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/monitor_PWU.py", line 24, in monitor_model
    raise Exception("Flask prediction failed.")
Exception: Flask prediction failed.
[2025-05-21T17:24:07.644+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=monitor_PWU, task_id=monitor_model, execution_date=20250521T172406, start_date=20250521T172407, end_date=20250521T172407
[2025-05-21T17:24:07.658+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 41 for task monitor_model (Flask prediction failed.; 230)
[2025-05-21T17:24:07.673+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-21T17:24:07.702+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T17:24:07.709+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
