{"timestamp":"2025-05-07T12:00:13.976017","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-05-07T12:00:13.976716","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/retrain_model_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-05-07T12:00:14.142977Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-07T12:00:14.143932Z","level":"info","event":" Previous state of the Task instance: queued","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-07T12:00:14.144548Z","level":"info","event":"Current task name:reload_model_task","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-07T12:00:14.145177Z","level":"info","event":"Dag name:retrain_model_dag","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-07T12:00:14.145750Z","level":"info","event":"✅ 최신 모델 경로: /app/models/trained_model_20250507_120008.pth","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-07T12:00:17.400362","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"ConnectionError","exc_value":"HTTPConnectionPool(host='flask-server', port=5000): Max retries exceeded with url: /reload_model (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f97b9eac710>: Failed to resolve 'flask-server' ([Errno -2] Name or service not known)\"))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/retrain_model_dag.py","lineno":25,"name":"call_reload_model"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/api.py","lineno":115,"name":"post"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/api.py","lineno":59,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py","lineno":589,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py","lineno":703,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":700,"name":"send"}]},{"exc_type":"MaxRetryError","exc_value":"HTTPConnectionPool(host='flask-server', port=5000): Max retries exceeded with url: /reload_model (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f97b9eac710>: Failed to resolve 'flask-server' ([Errno -2] Name or service not known)\"))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":667,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":519,"name":"increment"}]},{"exc_type":"NameResolutionError","exc_value":"<urllib3.connection.HTTPConnection object at 0x7f97b9eac710>: Failed to resolve 'flask-server' ([Errno -2] Name or service not known)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":493,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":445,"name":"request"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1333,"name":"endheaders"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1093,"name":"_send_output"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1037,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":276,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":205,"name":"_new_conn"}]},{"exc_type":"gaierror","exc_value":"[Errno -2] Name or service not known","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":198,"name":"_new_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":60,"name":"create_connection"},{"filename":"/usr/local/lib/python3.12/socket.py","lineno":978,"name":"getaddrinfo"}]}]}
{"timestamp":"2025-05-07T12:00:17.460216Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-07T12:00:17.460801Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-07T12:00:17.462048Z","level":"info","event":"Task:<Task(PythonOperator): reload_model_task>","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-07T12:00:17.463900Z","level":"info","event":"Failure caused by HTTPConnectionPool(host='flask-server', port=5000): Max retries exceeded with url: /reload_model (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f97b9eac710>: Failed to resolve 'flask-server' ([Errno -2] Name or service not known)\"))","chan":"stdout","logger":"task"}
