[2025-05-11T15:00:02.318+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-11T15:00:02.346+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitor_PWU.check_if_retrain_needed scheduled__2025-05-11T14:00:00+00:00 [queued]>
[2025-05-11T15:00:02.355+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitor_PWU.check_if_retrain_needed scheduled__2025-05-11T14:00:00+00:00 [queued]>
[2025-05-11T15:00:02.356+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-11T15:00:02.369+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): check_if_retrain_needed> on 2025-05-11 14:00:00+00:00
[2025-05-11T15:00:02.374+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=26931) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-11T15:00:02.374+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'monitor_PWU', 'check_if_retrain_needed', 'scheduled__2025-05-11T14:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/monitor_PWU.py', '--cfg-path', '/tmp/tmpjkgo_brw']
[2025-05-11T15:00:02.376+0000] {standard_task_runner.py:63} INFO - Started process 26932 to run task
[2025-05-11T15:00:02.376+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask check_if_retrain_needed
[2025-05-11T15:00:02.416+0000] {task_command.py:426} INFO - Running <TaskInstance: monitor_PWU.check_if_retrain_needed scheduled__2025-05-11T14:00:00+00:00 [running]> on host d6c25b332bd7
[2025-05-11T15:00:02.488+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monitor_PWU' AIRFLOW_CTX_TASK_ID='check_if_retrain_needed' AIRFLOW_CTX_EXECUTION_DATE='2025-05-11T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-11T14:00:00+00:00'
[2025-05-11T15:00:02.489+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-11T15:00:02.499+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-05-11T15:00:02.507+0000] {python.py:237} INFO - Done. Returned value was: end
[2025-05-11T15:00:02.508+0000] {branch.py:36} INFO - Branch into end
[2025-05-11T15:00:02.508+0000] {skipmixin.py:178} INFO - Following branch end
[2025-05-11T15:00:02.519+0000] {skipmixin.py:246} INFO - Skipping tasks [('trigger_retrain', -1)]
[2025-05-11T15:00:02.539+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-11T15:00:02.554+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=monitor_PWU, task_id=check_if_retrain_needed, execution_date=20250511T140000, start_date=20250511T150002, end_date=20250511T150002
[2025-05-11T15:00:02.590+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-11T15:00:02.611+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-11T15:00:02.614+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
