[2025-05-21T17:36:04.878+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-21T17:36:04.924+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitor_T3.monitor_model manual__2025-05-21T17:36:03.608749+00:00 [queued]>
[2025-05-21T17:36:04.940+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitor_T3.monitor_model manual__2025-05-21T17:36:03.608749+00:00 [queued]>
[2025-05-21T17:36:04.941+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-21T17:36:04.971+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): monitor_model> on 2025-05-21 17:36:03.608749+00:00
[2025-05-21T17:36:04.980+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'monitor_T3', 'monitor_model', 'manual__2025-05-21T17:36:03.608749+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/monitor_T3.py', '--cfg-path', '/tmp/tmpz5et03zn']
[2025-05-21T17:36:04.983+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask monitor_model
[2025-05-21T17:36:04.983+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=288) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-21T17:36:04.984+0000] {standard_task_runner.py:63} INFO - Started process 289 to run task
[2025-05-21T17:36:05.058+0000] {task_command.py:426} INFO - Running <TaskInstance: monitor_T3.monitor_model manual__2025-05-21T17:36:03.608749+00:00 [running]> on host 2b70c836932b
[2025-05-21T17:36:05.179+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monitor_T3' AIRFLOW_CTX_TASK_ID='monitor_model' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T17:36:03.608749+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T17:36:03.608749+00:00'
[2025-05-21T17:36:05.180+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-21T17:36:05.263+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-21T17:36:05.264+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/monitor_T3.py", line 26, in monitor_model
    raise Exception(f"Flask prediction failed.\nStatus: {res.status_code}\nMessage: {res.text}")
Exception: Flask prediction failed.
Status: 500
Message: {"error":"invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number"}

[2025-05-21T17:36:05.275+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=monitor_T3, task_id=monitor_model, execution_date=20250521T173603, start_date=20250521T173604, end_date=20250521T173605
[2025-05-21T17:36:05.293+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 48 for task monitor_model (Flask prediction failed.
Status: 500
Message: {"error":"invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number"}
; 289)
[2025-05-21T17:36:05.319+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-21T17:36:05.345+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T17:36:05.353+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
