[2025-05-12T08:23:56.469+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-12T08:23:56.499+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retrain_PWU_dag.train_PWU manual__2025-05-12T08:23:55.571507+00:00 [queued]>
[2025-05-12T08:23:56.508+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retrain_PWU_dag.train_PWU manual__2025-05-12T08:23:55.571507+00:00 [queued]>
[2025-05-12T08:23:56.509+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-12T08:23:56.522+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): train_PWU> on 2025-05-12 08:23:55.571507+00:00
[2025-05-12T08:23:56.528+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'retrain_PWU_dag', 'train_PWU', 'manual__2025-05-12T08:23:55.571507+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/retrain_PWU_dag.py', '--cfg-path', '/tmp/tmpuvdkl_gi']
[2025-05-12T08:23:56.530+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask train_PWU
[2025-05-12T08:23:56.532+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1517) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-12T08:23:56.533+0000] {standard_task_runner.py:63} INFO - Started process 1518 to run task
[2025-05-12T08:23:56.574+0000] {task_command.py:426} INFO - Running <TaskInstance: retrain_PWU_dag.train_PWU manual__2025-05-12T08:23:55.571507+00:00 [running]> on host 6c14bac78271
[2025-05-12T08:23:56.653+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='retrain_PWU_dag' AIRFLOW_CTX_TASK_ID='train_PWU' AIRFLOW_CTX_EXECUTION_DATE='2025-05-12T08:23:55.571507+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-12T08:23:55.571507+00:00'
[2025-05-12T08:23:56.654+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-12T08:23:56.666+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-12T08:23:56.667+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/train_PWU.py']
[2025-05-12T08:23:56.674+0000] {subprocess.py:86} INFO - Output:
[2025-05-12T08:24:00.036+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-12T08:24:00.036+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/train_PWU.py", line 15, in <module>
[2025-05-12T08:24:00.038+0000] {subprocess.py:93} INFO -     from Model.T3.Informer import Informer  # T3 정의가 여기 있어야 함
[2025-05-12T08:24:00.039+0000] {subprocess.py:93} INFO -     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-12T08:24:00.039+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'Model'
[2025-05-12T08:24:00.476+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-12T08:24:00.477+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-12T08:24:00.486+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-12T08:24:00.490+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=retrain_PWU_dag, task_id=train_PWU, execution_date=20250512T082355, start_date=20250512T082356, end_date=20250512T082400
[2025-05-12T08:24:00.503+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task train_PWU (Bash command failed. The command returned a non-zero exit code 1.; 1518)
[2025-05-12T08:24:00.519+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-12T08:24:00.541+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-12T08:24:00.546+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
