[2025-05-12T08:08:00.053+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-12T08:08:00.082+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retrain_PWU_dag.train_PWU manual__2025-05-12T08:07:59.075216+00:00 [queued]>
[2025-05-12T08:08:00.090+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retrain_PWU_dag.train_PWU manual__2025-05-12T08:07:59.075216+00:00 [queued]>
[2025-05-12T08:08:00.091+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-12T08:08:00.107+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): train_PWU> on 2025-05-12 08:07:59.075216+00:00
[2025-05-12T08:08:00.112+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'retrain_PWU_dag', 'train_PWU', 'manual__2025-05-12T08:07:59.075216+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/retrain_PWU_dag.py', '--cfg-path', '/tmp/tmpuiu5n8ja']
[2025-05-12T08:08:00.114+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask train_PWU
[2025-05-12T08:08:00.116+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=403) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-12T08:08:00.117+0000] {standard_task_runner.py:63} INFO - Started process 404 to run task
[2025-05-12T08:08:00.169+0000] {task_command.py:426} INFO - Running <TaskInstance: retrain_PWU_dag.train_PWU manual__2025-05-12T08:07:59.075216+00:00 [running]> on host 6c14bac78271
[2025-05-12T08:08:00.248+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='retrain_PWU_dag' AIRFLOW_CTX_TASK_ID='train_PWU' AIRFLOW_CTX_EXECUTION_DATE='2025-05-12T08:07:59.075216+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-12T08:07:59.075216+00:00'
[2025-05-12T08:08:00.249+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-12T08:08:00.260+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-12T08:08:00.261+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/train_PWU.py']
[2025-05-12T08:08:00.269+0000] {subprocess.py:86} INFO - Output:
[2025-05-12T08:08:04.037+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-12T08:08:04.038+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/train_PWU.py", line 13, in <module>
[2025-05-12T08:08:04.040+0000] {subprocess.py:93} INFO -     from Model.PWU import Informer  # Informer 정의가 여기 있어야 함
[2025-05-12T08:08:04.040+0000] {subprocess.py:93} INFO -     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-12T08:08:04.041+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'Model'
[2025-05-12T08:08:04.515+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-12T08:08:04.516+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-12T08:08:04.526+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-12T08:08:04.530+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=retrain_PWU_dag, task_id=train_PWU, execution_date=20250512T080759, start_date=20250512T080800, end_date=20250512T080804
[2025-05-12T08:08:04.547+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task train_PWU (Bash command failed. The command returned a non-zero exit code 1.; 404)
[2025-05-12T08:08:04.587+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-12T08:08:04.610+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-12T08:08:04.617+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
