[2025-05-21T17:58:23.853+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-21T17:58:23.933+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitor_T3.monitor_model manual__2025-05-21T17:58:22.401056+00:00 [queued]>
[2025-05-21T17:58:23.953+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitor_T3.monitor_model manual__2025-05-21T17:58:22.401056+00:00 [queued]>
[2025-05-21T17:58:23.954+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-21T17:58:23.988+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): monitor_model> on 2025-05-21 17:58:22.401056+00:00
[2025-05-21T17:58:24.007+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'monitor_T3', 'monitor_model', 'manual__2025-05-21T17:58:22.401056+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/monitor_T3.py', '--cfg-path', '/tmp/tmpsvazkr0w']
[2025-05-21T17:58:24.011+0000] {standard_task_runner.py:91} INFO - Job 59: Subtask monitor_model
[2025-05-21T17:58:24.013+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=186) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-21T17:58:24.014+0000] {standard_task_runner.py:63} INFO - Started process 200 to run task
[2025-05-21T17:58:24.093+0000] {task_command.py:426} INFO - Running <TaskInstance: monitor_T3.monitor_model manual__2025-05-21T17:58:22.401056+00:00 [running]> on host 20faf461a3a5
[2025-05-21T17:58:24.272+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monitor_T3' AIRFLOW_CTX_TASK_ID='monitor_model' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T17:58:22.401056+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T17:58:22.401056+00:00'
[2025-05-21T17:58:24.274+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-21T17:58:24.392+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-21T17:58:24.395+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/monitor_T3.py", line 26, in monitor_model
    raise Exception(f"Flask prediction failed.\nStatus: {res.status_code}\nMessage: {res.text}")
Exception: Flask prediction failed.
Status: 500
Message: {"error":"invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number"}

[2025-05-21T17:58:24.410+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=monitor_T3, task_id=monitor_model, execution_date=20250521T175822, start_date=20250521T175823, end_date=20250521T175824
[2025-05-21T17:58:24.429+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 59 for task monitor_model (Flask prediction failed.
Status: 500
Message: {"error":"invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number"}
; 200)
[2025-05-21T17:58:24.481+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-21T17:58:24.547+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T17:58:24.557+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
