[2025-05-12T08:07:50.656+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-12T08:07:50.683+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retrain_PWU_dag.train_PWU manual__2025-05-12T08:07:11.390984+00:00 [queued]>
[2025-05-12T08:07:50.690+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retrain_PWU_dag.train_PWU manual__2025-05-12T08:07:11.390984+00:00 [queued]>
[2025-05-12T08:07:50.691+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-12T08:07:50.704+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): train_PWU> on 2025-05-12 08:07:11.390984+00:00
[2025-05-12T08:07:50.710+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'retrain_PWU_dag', 'train_PWU', 'manual__2025-05-12T08:07:11.390984+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/retrain_PWU_dag.py', '--cfg-path', '/tmp/tmp2i0vwb1_']
[2025-05-12T08:07:50.712+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask train_PWU
[2025-05-12T08:07:50.713+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=379) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-12T08:07:50.714+0000] {standard_task_runner.py:63} INFO - Started process 380 to run task
[2025-05-12T08:07:50.755+0000] {task_command.py:426} INFO - Running <TaskInstance: retrain_PWU_dag.train_PWU manual__2025-05-12T08:07:11.390984+00:00 [running]> on host 6c14bac78271
[2025-05-12T08:07:50.831+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='retrain_PWU_dag' AIRFLOW_CTX_TASK_ID='train_PWU' AIRFLOW_CTX_EXECUTION_DATE='2025-05-12T08:07:11.390984+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-12T08:07:11.390984+00:00'
[2025-05-12T08:07:50.832+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-12T08:07:50.843+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-12T08:07:50.844+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/train_PWU.py']
[2025-05-12T08:07:50.851+0000] {subprocess.py:86} INFO - Output:
[2025-05-12T08:07:57.154+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-12T08:07:57.155+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/train_PWU.py", line 13, in <module>
[2025-05-12T08:07:57.156+0000] {subprocess.py:93} INFO -     from Model.PWU import Informer  # Informer 정의가 여기 있어야 함
[2025-05-12T08:07:57.156+0000] {subprocess.py:93} INFO -     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-12T08:07:57.157+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'Model'
[2025-05-12T08:07:57.986+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-12T08:07:57.987+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-12T08:07:57.996+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-12T08:07:58.002+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=retrain_PWU_dag, task_id=train_PWU, execution_date=20250512T080711, start_date=20250512T080750, end_date=20250512T080758
[2025-05-12T08:07:58.020+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task train_PWU (Bash command failed. The command returned a non-zero exit code 1.; 380)
[2025-05-12T08:07:58.050+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-12T08:07:58.070+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-12T08:07:58.076+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
