[2025-05-17T18:00:01.546+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-17T18:00:01.586+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitor_T3.check_if_retrain_needed scheduled__2025-05-17T17:00:00+00:00 [queued]>
[2025-05-17T18:00:01.601+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitor_T3.check_if_retrain_needed scheduled__2025-05-17T17:00:00+00:00 [queued]>
[2025-05-17T18:00:01.602+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-17T18:00:01.623+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): check_if_retrain_needed> on 2025-05-17 17:00:00+00:00
[2025-05-17T18:00:01.631+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=21839) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-17T18:00:01.632+0000] {standard_task_runner.py:63} INFO - Started process 21840 to run task
[2025-05-17T18:00:01.631+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'monitor_T3', 'check_if_retrain_needed', 'scheduled__2025-05-17T17:00:00+00:00', '--job-id', '398', '--raw', '--subdir', 'DAGS_FOLDER/monitor_T3.py', '--cfg-path', '/tmp/tmp23ass_tq']
[2025-05-17T18:00:01.634+0000] {standard_task_runner.py:91} INFO - Job 398: Subtask check_if_retrain_needed
[2025-05-17T18:00:01.692+0000] {task_command.py:426} INFO - Running <TaskInstance: monitor_T3.check_if_retrain_needed scheduled__2025-05-17T17:00:00+00:00 [running]> on host b91ac73f2b68
[2025-05-17T18:00:01.826+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monitor_T3' AIRFLOW_CTX_TASK_ID='check_if_retrain_needed' AIRFLOW_CTX_EXECUTION_DATE='2025-05-17T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-17T17:00:00+00:00'
[2025-05-17T18:00:01.827+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-17T18:00:01.854+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-05-17T18:00:01.870+0000] {python.py:237} INFO - Done. Returned value was: trigger_retrain
[2025-05-17T18:00:01.870+0000] {branch.py:36} INFO - Branch into trigger_retrain
[2025-05-17T18:00:01.871+0000] {skipmixin.py:178} INFO - Following branch trigger_retrain
[2025-05-17T18:00:01.893+0000] {skipmixin.py:246} INFO - Skipping tasks [('end', -1)]
[2025-05-17T18:00:01.926+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-17T18:00:01.953+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=monitor_T3, task_id=check_if_retrain_needed, execution_date=20250517T170000, start_date=20250517T180001, end_date=20250517T180001
[2025-05-17T18:00:02.008+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-17T18:00:02.040+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-17T18:00:02.043+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
